#!/bin/sh

alpha='dd'

# Paleta personalizada
background='#262626'
selection='#585B70' 
comment='#DDB6F2'         
text='#ffffff'
yellow='#f1fa8c'          
orange='#FAB387'          
red='#F38BA8'             
magenta='#bd93f9'         
blue='#6272a4'            
cyan='#FFFFFF'            
green='#50fa7b'           

i3lock \
    --pointer default \
    --image=$HOME/.local/share/wallpapers/dreamscape.png \
    --scale \
    --insidever-color=$selection$alpha \
    --insidewrong-color=$selection$alpha \
    --inside-color=$selection$alpha \
    --ringver-color=$green$alpha \
    --ringwrong-color=$red$alpha \
    --ringver-color=$green$alpha \
    --ringwrong-color=$red$alpha \
    --ring-color=$blue$alpha \
    --line-uses-ring \
    --keyhl-color=$magenta$alpha \
    --bshl-color=$orange$alpha \
    --separator-color=$selection$alpha \
    --verif-color=$green \
    --wrong-color=$red \
    --modif-color=$red \
    --layout-color=$blue \
    --date-color=$text \
    --time-color=$text \
    --screen 1 \
    --blur 1 \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A %e %B %Y" \
    --verif-text=" Checking" \
    --wrong-text="󰅙 Wrong pswd" \
    --noinput="No Input" \
    --lock-text=" Locking" \
    --lockfailed=" Lock Failed" \
    --radius=120 \
    --ring-width=10 \
    --pass-media-keys \
    --pass-screen-keys \
    --pass-volume-keys \
    --verif-align=center \
    --wrong-align=center \
    --time-font="FiraCode Nerd Font Mono" \
    --date-font="FiraCode Nerd Font Mono" \
    --layout-font="FiraCode Nerd Font Mono" \
    --verif-font="FiraCode Nerd Font Mono" \
    --wrong-font="FiraCode Nerd Font Mono"

