# Tema principal
include themes/mocha.conf

# Colores para el diff kitten
include themes/diff-mocha.conf

# fuentes
font_family      FiraCode Nerd Font Mono
bold_font        FiraCode Nerd Font Mono Bold
italic_font      FiraCode Nerd Font Mono
bold_italic_font FiraCode Nerd Font Mono Bold


# ligaduras
disable_ligatures never

# fallback emojis
symbol_map U+1F300-U+1FAFF Noto Color Emoji

# Sonido
enable_audio_bell no
visual_bell_duration 0

#quitar confirmacion de cerrar ventana
confirm_os_window_close 0

