# tema
include dracula.conf

# fuentes
font_family FiraCode Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

# ligaduras
disable_ligatures never

# fallback emojis
fallback_fonts Noto color Emoji

# Sonido
enable_audio_bell no
visual_bell_duration 0

#quitar confirmacion de cerrar ventana
confirm_os_window_close 0

