# Navegar entre paneles con Alt + flechas
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Redimensionar con Alt+Shift+Flechas
bind -n M-S-Left  resize-pane -L 1
bind -n M-S-Down  resize-pane -D 1
bind -n M-S-Up    resize-pane -U 1
bind -n M-S-Right resize-pane -R 1

# Navegar entre paneles con Control+h/j/k/l
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

# Redimensionar con Ctrl+Alt+h/j/k/l
bind -n C-M-S-h resize-pane -L 1
bind -n C-M-S-j resize-pane -D 1
bind -n C-M-S-k resize-pane -U 1
bind -n C-M-S-l resize-pane -R 1
