# ===========================
# Barra de estado
# ===========================

# Colores generales de la barra (fondo y texto)
set -g status-style bg=#1e1e2e,fg=#cdd6f4

# ===========================
# Lado izquierdo
# ===========================

# Muestra el nombre de la sesión (#S)
# Ejemplo: "dev", "server", "work"
set -g status-left "#[fg=#89b4fa,bold] #S "

# ===========================
# Lado derecho
# ===========================

# Muestra la hora y la fecha
# %H:%M     -> 14:35
# %d/%m/%Y  -> 19/07/2026
set -g status-right "#[fg=#f9e2af]%H:%M #[fg=#94e2d5]%d/%m/%Y"

# ===========================
# Ventanas
# ===========================

# Apariencia de la ventana ACTIVA
# fg = color del texto
# bg = color del fondo
# bold = texto en negrita
setw -g window-status-current-style fg=#1e1e2e,bg=#89b4fa,bold

# Apariencia de las ventanas INACTIVAS
setw -g window-status-style fg=#bac2de,bg=default

# Separador entre ventanas
setw -g window-status-separator " "
