import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[font]
size = 10.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold" }

[window]
# Espacio interno entre el texto y los bordes
padding = { x = 5, y = 5 }

# No cambiar automáticamente el tamaño de la terminal
dynamic_title = true

# Opacidad de la ventana
opacity = 0.95

# Decoraciones de la ventana
decorations = "full"

# Estado inicial
startup_mode = "Windowed"

[scrolling]
# Líneas que Alacritty conserva en memoria
history = 10000

# Scroll con el mouse
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
