[colors]
background = #262626
foreground = #FFFFFF
accent     = #bd93f9
mauve      = #DDB6F2
crust      = #181825
peach      = #FAB387
alert      = #F38BA8
disabled   = #585B70
primary    = #89B4FA
green      = #519872

[bar/bar1]
monitor = ${env:MONITOR:}
width = 100%
height = 32
radius = 1
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 2
border-color = ${colors.accent}
padding = 2
padding-left = 1
padding-right = 1

wm-restack = i3
override-redirect = false

cursor-click = pointer

font-0 = "FiraCode Nerd Font Mono:size=10;2"
font-1 = "JetBrains Mono Nerd Font:size=10;2"
font-2 = "FontAwesome:size=10;2"

modules-left = powermenu start_menu date_time i3
modules-center = memory cpu backlight battery temperature
modules-right = network pulseaudio systray

module-margin-left = 1
module-margin-right = 1

; [module/systray]
; type = internal/tray
; format = <tray>
; tray-size = 60%+1
; tray-spacing = 5px
; tray-padding = 1px
;
[module/systray]
type = internal/tray

format = <tray>
tray-size = 60%+2
tray-spacing = 5px
tray-padding = 1px

format-margin = 6px
format-padding = 0px

format-background = ${colors.background}
format-foreground = ${colors.accent}

[module/powermenu]
type = custom/text
format = "  "
click-left = ~/.config/polybar/scripts/powermenu_script/power_menu.sh
label-background = ${colors.accent}
label-foreground = ${colors.foreground}


[module/start_menu]
type = custom/text
click-left = rofi -show drun -me-select-entry '' -me-accept-entry MousePrimary
format = " Menu"
label = %content%
label-padding = 2
label-background = ${colors.accent}
label-foreground = ${colors.foreground}

[module/i3]
type = internal/i3

pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true

format = <label-state>

label-focused = %icon%
label-focused-foreground = ${colors.background}
label-focused-background = ${colors.accent}
label-focused-padding = 2

label-unfocused = %icon%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 2

label-visible = %icon%
label-visible-foreground = ${colors.primary}
label-visible-padding = 2

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.background}
label-urgent-padding = 2

ws-icon-1 = 1;
ws-icon-2 = 2;
ws-icon-3 = 3;
ws-icon-4 = 4;
ws-icon-5 = 5;
ws-icon-6 = 6;󰈙
ws-icon-7 = 7;
ws-icon-8 = 8;
ws-icon-9 = 9;
ws-icon-0 = 0;
ws-icon-default = 

[module/date_time]
type = internal/date
interval = 1

; Formato principal (por defecto)
date = %I:%M:%S %p
label = "%date%"
format-prefix = " "
format-prefix-foreground = ${colors.accent}
label-foreground = ${colors.foreground}

; Formato alternativo (al hacer click)
date-alt = %d,%b,%Y
label-alt = "%date-alt%"

[module/memory]
type = internal/memory
interval = 2
format-prefix = ""  
format-prefix-foreground = ${colors.accent}
label = %used%
label-foreground = ${colors.foreground}
label-padding = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "" 
format-prefix-foreground = ${colors.accent}
label = %percentage:2%%
label-foreground = ${colors.foreground}
label-padding = 1

[module/battery]
type = internal/battery
format-prefix = "󰁹"
format-prefix-foreground = ${colors.primary}
full-at = 99

format-charging = <animation-charging> <label-charging>
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}

format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-0-foreground = ${colors.green}
ramp-capacity-1-foreground = ${colors.primary}
ramp-capacity-2-foreground = ${colors.peach}
ramp-capacity-3-foreground = ${colors.alert}
ramp-capacity-4-foreground = ${colors.alert}

low-at = 5
format-low = <ramp-capacity>
format-critical = <ramp-capacity>
format-full = 󰁹 <label-full>
label-full = 100%
format-full-foreground = ${colors.green}
battery = BAT1
adapter = ACAD
poll-interval = 5

[module/wlan]
type = internal/network
interface-type = wireless
interface = wlo1
label-connected =  %essid% %local_ip%
label-disconnected = %ifname% 󰖪 disconnected
format-foreground = ${colors.primary}
format-padding = 5

[module/eth]
type = internal/network
interface-type = wired
interface = enp2s0
label-connected = 󰈀 %local_ip%
label-disconnected = %ifname% 󰈂 disconnected
format-foreground = ${colors.primary}

[module/network]
type = custom/script
exec = "$HOME/.config/polybar/scripts/network_script/network.sh"
interval = 2
label-font = 2
format-foreground = ${colors.foreground}
format-background = ${colors.background}



[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.accent}
ramp-volume-foreground = ${colors.accent}

label-volume = %percentage%%
label-muted = "  Muted"
label-muted-foreground = ${colors.disabled}

scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

[module/backlight]
type = internal/backlight
card = amdgpu_bl1

format = <ramp> <label>
format-padding = 2px

label = %percentage%%
label-font = 3

ramp-0 = 󰃞
ramp-1 = 󰃟
ramp-2 = 󰃠 

ramp-0-foreground = ${colors.green}
ramp-1-foreground = ${colors.peach}
ramp-2-foreground = ${colors.accent}

[module/temperature]
type = internal/temperature
interval = 1

thermal-zone = 0
base-temperature = 20
warn-temperature = 60

units = false

format = <ramp> <label>
format-warn = <ramp> <label-warn>

label = %temperature-c%
label-font = 2
label-foreground = ${colors.foreground}

label-warn = %temperature-c%
label-warn-foreground = ${colors.foreground}
label-warn-font = 2

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

ramp-0-foreground = ${colors.mauve}
ramp-1-foreground = ${colors.green}
ramp-2-foreground = ${colors.peach}
ramp-3-foreground = ${colors.alert}
ramp-4-foreground = ${colors.alert}

ramp-font = 2

[settings]
screenchange-reload = true
pseudo-transparency = true
